package container

import (
	"archive/tar"
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/image"
	"github.com/docker/docker/client"

	"github.com/Devon-White/claude-bunker/internal/config"
)

// BuildResult holds information about a completed image build.
type BuildResult struct {
	// BaseImageDigest is the digest of the pulled pre-built base image, if one
	// was used. Empty when the image was built locally.
	BaseImageDigest string
}

// PullBaseImage attempts to pull a pre-built base image from GHCR and tag it
// locally as imageTag. Returns the image digest on success.
func PullBaseImage(ctx context.Context, cli *client.Client, baseImageRef string) (digest string, err error) {
	pullCtx, cancel := context.WithTimeout(ctx, 60*time.Second)
	defer cancel()

	reader, err := cli.ImagePull(pullCtx, baseImageRef, image.PullOptions{})
	if err != nil {
		return "", fmt.Errorf("pulling %s: %w", baseImageRef, err)
	}
	defer reader.Close()

	// Consume the pull output to completion, capturing the digest.
	scanner := bufio.NewScanner(reader)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		var msg struct {
			Status string `json:"status"`
			Error  string `json:"error"`
			ID     string `json:"id"`
			Aux    *struct {
				Digest string `json:"Digest"`
			} `json:"aux"`
		}
		if err := json.Unmarshal(scanner.Bytes(), &msg); err != nil {
			continue
		}
		if msg.Error != "" {
			return "", fmt.Errorf("pull error: %s", msg.Error)
		}
		if msg.Aux != nil && msg.Aux.Digest != "" {
			digest = msg.Aux.Digest
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("reading pull output: %w", err)
	}

	// If we didn't capture the digest from the stream, inspect the image.
	if digest == "" {
		inspect, _, err := cli.ImageInspectWithRaw(ctx, baseImageRef)
		if err != nil {
			return "", fmt.Errorf("inspecting pulled image: %w", err)
		}
		if len(inspect.RepoDigests) > 0 {
			digest = inspect.RepoDigests[0]
		}
	}

	return digest, nil
}

// BuildImage builds the Docker image entirely from in-memory and embedded content.
// No .devcontainer/ directory is needed — the Dockerfile is generated by Go,
// and scripts are embedded via go:embed.
//
// When version is set (non-dev), it first attempts to pull a pre-built base
// image from GHCR, falling back to a local build on failure.
//
// When projectCfg contains features or apt packages, it resolves them, generates
// a merged Dockerfile, and includes feature files in the build context.
// If streamOutput is true, build output is streamed to stdout.
func BuildImage(ctx context.Context, cli *client.Client, imageTag string, streamOutput bool, projectCfg config.ProjectConfig, version string) (BuildResult, error) {
	var result BuildResult
	baseRef := BaseImageRef(version)

	// --- Fast path: try pulling pre-built base image ---
	if baseRef != "" {
		if !projectCfg.HasGeneratedLayers() {
			// No dynamic layers — pull and tag directly as the final image.
			digest, err := PullBaseImage(ctx, cli, baseRef)
			if err == nil {
				// Tag the pulled image as the local image tag.
				if tagErr := cli.ImageTag(ctx, baseRef, imageTag); tagErr != nil {
					return BuildResult{}, fmt.Errorf("tagging pulled image: %w", tagErr)
				}
				result.BaseImageDigest = digest
				return result, nil
			}
			// Pull failed — fall through to local build.
			fmt.Fprintf(os.Stderr, "[claude-bunker] Pre-built image pull failed, building locally: %v\n", err)
		} else {
			// Has dynamic layers — pull base, then build dynamic layers on top.
			digest, err := PullBaseImage(ctx, cli, baseRef)
			if err == nil {
				result.BaseImageDigest = digest
				return result, buildDynamicLayers(ctx, cli, imageTag, baseRef, streamOutput, projectCfg)
			}
			// Pull failed — fall through to full local build.
			fmt.Fprintf(os.Stderr, "[claude-bunker] Pre-built image pull failed, building locally: %v\n", err)
		}
	}

	// --- Fallback: full local build ---
	return result, buildLocal(ctx, cli, imageTag, streamOutput, projectCfg)
}

// buildDynamicLayers builds only the dynamic (project-specific) layers on top
// of a pre-pulled base image.
func buildDynamicLayers(ctx context.Context, cli *client.Client, imageTag, baseRef string, streamOutput bool, projectCfg config.ProjectConfig) error {
	features, cleanup, err := ResolveFeatures(projectCfg.Features)
	if err != nil {
		return fmt.Errorf("resolving features: %w", err)
	}
	defer cleanup()

	// Generate a minimal Dockerfile that starts FROM the pulled base image
	// and adds only the dynamic layers (apt, features, env).
	baseContent := "FROM " + baseRef + "\n\n"
	// The pre-built image already ends with USER claude-bunker, so strip it
	// for the merged Dockerfile to re-add at the end.
	baseContent += "USER root\n"

	merged, err := GenerateDockerfile(baseContent, features, projectCfg.Apt, projectCfg.Env)
	if err != nil {
		return fmt.Errorf("generating dynamic Dockerfile: %w", err)
	}

	tarBuf, err := buildContextTar(merged, features)
	if err != nil {
		return fmt.Errorf("creating build context: %w", err)
	}

	return runBuild(ctx, cli, imageTag, tarBuf, streamOutput)
}

// buildLocal performs the full local image build (current behavior).
func buildLocal(ctx context.Context, cli *client.Client, imageTag string, streamOutput bool, projectCfg config.ProjectConfig) error {
	baseDockerfile := GenerateBaseDockerfile()

	var tarBuf *bytes.Buffer
	var cleanupFn func()

	if projectCfg.HasGeneratedLayers() {
		features, cleanup, err := ResolveFeatures(projectCfg.Features)
		if err != nil {
			return fmt.Errorf("resolving features: %w", err)
		}
		cleanupFn = cleanup

		baseContent := stripTrailingUser(baseDockerfile)
		merged, err := GenerateDockerfile(baseContent, features, projectCfg.Apt, projectCfg.Env)
		if err != nil {
			cleanupFn()
			return fmt.Errorf("generating Dockerfile: %w", err)
		}

		tarBuf, err = buildContextTar(merged, features)
		if err != nil {
			cleanupFn()
			return fmt.Errorf("creating build context: %w", err)
		}
	} else {
		var err error
		tarBuf, err = buildContextTar(baseDockerfile, nil)
		if err != nil {
			return fmt.Errorf("creating build context: %w", err)
		}
	}

	if cleanupFn != nil {
		defer cleanupFn()
	}

	return runBuild(ctx, cli, imageTag, tarBuf, streamOutput)
}

// runBuild executes a Docker image build with the standard build args.
func runBuild(ctx context.Context, cli *client.Client, imageTag string, tarBuf *bytes.Buffer, streamOutput bool) error {
	buildArgs := map[string]*string{}

	tz := os.Getenv("TZ")
	if tz == "" {
		tz = "UTC"
	}
	buildArgs["TZ"] = &tz

	gitDeltaVersion := GitDeltaVersion
	buildArgs["GIT_DELTA_VERSION"] = &gitDeltaVersion

	zshVersion := ZshInDockerVersion
	buildArgs["ZSH_IN_DOCKER_VERSION"] = &zshVersion

	resp, err := cli.ImageBuild(ctx, tarBuf, types.ImageBuildOptions{
		Tags:       []string{imageTag},
		Dockerfile: "Dockerfile",
		BuildArgs:  buildArgs,
		Remove:     true,
	})
	if err != nil {
		return fmt.Errorf("starting image build: %w", err)
	}
	defer resp.Body.Close()

	scanner := bufio.NewScanner(resp.Body)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		var msg struct {
			Stream string `json:"stream"`
			Error  string `json:"error"`
		}
		if err := json.Unmarshal(scanner.Bytes(), &msg); err != nil {
			continue
		}
		if msg.Error != "" {
			return fmt.Errorf("build error: %s", msg.Error)
		}
		if streamOutput && msg.Stream != "" {
			fmt.Print(msg.Stream)
		}
	}
	if err := scanner.Err(); err != nil {
		return fmt.Errorf("reading build output: %w", err)
	}

	return nil
}

// ImageExists checks if the given image tag exists locally.
func ImageExists(ctx context.Context, cli *client.Client, imageTag string) bool {
	_, _, err := cli.ImageInspectWithRaw(ctx, imageTag)
	return err == nil
}

// stripTrailingUser removes the final "USER <username>" line from a Dockerfile
// so it can be re-added after feature layers.
func stripTrailingUser(dockerfile string) string {
	lines := strings.Split(dockerfile, "\n")
	// Walk backward to find the last USER instruction
	for i := len(lines) - 1; i >= 0; i-- {
		trimmed := strings.TrimSpace(lines[i])
		if trimmed == "" {
			continue
		}
		if strings.HasPrefix(strings.ToUpper(trimmed), "USER ") {
			lines = append(lines[:i], lines[i+1:]...)
			break
		}
		break // stop at the first non-empty, non-USER line
	}
	return strings.Join(lines, "\n")
}

// buildContextTar creates a tar archive from the Dockerfile, embedded scripts,
// and optional feature directories. When features is nil, only the base
// context (Dockerfile + scripts) is included.
func buildContextTar(dockerfile string, features []ResolvedFeature) (*bytes.Buffer, error) {
	buf := new(bytes.Buffer)
	tw := tar.NewWriter(buf)

	// Use a fixed timestamp for reproducible builds / consistent Docker cache hits.
	modTime := time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)

	if err := addTarEntry(tw, "Dockerfile", []byte(dockerfile), 0644, modTime); err != nil {
		return nil, fmt.Errorf("adding Dockerfile: %w", err)
	}
	if err := addTarEntry(tw, "init-firewall.sh", InitFirewallScript(), 0755, modTime); err != nil {
		return nil, fmt.Errorf("adding init-firewall.sh: %w", err)
	}
	if err := addTarEntry(tw, "tmux.conf", TmuxConf(), 0644, modTime); err != nil {
		return nil, fmt.Errorf("adding tmux.conf: %w", err)
	}

	// Add feature directories under _features/<id>/
	for _, f := range features {
		featureBase := filepath.Clean(f.InstallDir)
		err := filepath.Walk(featureBase, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if info.IsDir() {
				return nil
			}

			relPath, err := filepath.Rel(featureBase, path)
			if err != nil {
				return err
			}
			relPath = strings.ReplaceAll(relPath, "\\", "/")

			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}

			tarPath := "_features/" + f.ID + "/" + relPath
			mode := int64(info.Mode().Perm())
			hdr := &tar.Header{
				Name:    tarPath,
				Mode:    mode,
				Size:    int64(len(data)),
				ModTime: info.ModTime(),
			}
			if err := tw.WriteHeader(hdr); err != nil {
				return err
			}
			if _, err := tw.Write(data); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return nil, fmt.Errorf("adding feature %s: %w", f.ID, err)
		}
	}

	if err := tw.Close(); err != nil {
		return nil, err
	}

	return buf, nil
}

// addTarEntry adds a single file entry to a tar writer.
func addTarEntry(tw *tar.Writer, name string, data []byte, mode int64, modTime time.Time) error {
	hdr := &tar.Header{
		Name:    name,
		Mode:    mode,
		Size:    int64(len(data)),
		ModTime: modTime,
	}
	if err := tw.WriteHeader(hdr); err != nil {
		return err
	}
	_, err := tw.Write(data)
	return err
}
