package container

import (
	"archive/tar"
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/image"
	"github.com/docker/docker/client"

	"github.com/Devon-White/claude-bunker/internal/config"
)

// reproducibleModTime is a fixed timestamp used for all build context tar
// entries to ensure reproducible builds and consistent Docker cache hits.
var reproducibleModTime = time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)

// BuildCache holds pre-computed build artifacts (Dockerfile, scripts) so that
// BuildImage can reuse values already computed during fingerprinting instead
// of regenerating them. All fields are optional — nil/empty means recompute.
type BuildCache struct {
	Dockerfile string
	Scripts    []BuildContextFile
}

// BuildImageOpts holds all options for building a Docker image.
type BuildImageOpts struct {
	ImageTag     string
	StreamOutput bool
	ProjectCfg   config.ProjectConfig
	Version      string
	NoCache      bool
	LogFn        func(string)
	Cache        *BuildCache
	Workspace    string
}

// BuildImage builds the Docker image entirely from in-memory and embedded content.
// No .devcontainer/ directory is needed — the Dockerfile is generated by Go,
// and scripts are embedded via go:embed.
//
// For release builds, attempts to pull the pre-built GHCR base image and use it
// as FROM instead of building from scratch. If StreamOutput is true, full build
// output is streamed to stdout. Otherwise, only Step N/M progress lines are
// emitted via LogFn.
func BuildImage(ctx context.Context, cli *client.Client, opts BuildImageOpts) error {

	// Extract optional cached artifacts to avoid recomputing what was already
	// generated during fingerprinting.
	var cached BuildCache
	if opts.Cache != nil {
		cached = *opts.Cache
	}

	baseRef := BaseImageRef(opts.Version)
	hasProjectLayers := opts.ProjectCfg.HasGeneratedLayers()

	// Pull the GHCR base image concurrently with feature resolution.
	// Skip pull when noCache is set (--rebuild) or for dev builds.
	pullCh := make(chan bool, 1)
	if baseRef != "" && !opts.NoCache {
		go func() { pullCh <- tryPullBaseImage(ctx, cli, baseRef) }()
	} else {
		pullCh <- false
	}

	// Resolve features concurrently with pull.
	var features []ResolvedFeature
	var cleanupFn func()
	if hasProjectLayers {
		var err error
		features, cleanupFn, err = ResolveFeatures(opts.ProjectCfg.Features, opts.Workspace, opts.NoCache)
		if err != nil {
			return fmt.Errorf("resolving features: %w", err)
		}
		defer cleanupFn()
	}

	pulled := <-pullCh

	// Fast path: pulled base image + no project layers → just tag and done.
	if pulled && !hasProjectLayers {
		return cli.ImageTag(ctx, baseRef, opts.ImageTag)
	}

	// Generate Dockerfile — 3 cases:
	var dockerfile string
	var err error
	genOpts := DockerfileOpts{
		Features:        features,
		UserEnv:         opts.ProjectCfg.Env,
		OnCreateCommand: opts.ProjectCfg.OnCreateCommand,
	}
	if pulled && hasProjectLayers {
		// Minimal: FROM <ghcr-ref> + project layers only
		genOpts.BaseDockerfile = "FROM " + baseRef + "\n"
		dockerfile, err = GenerateDockerfile(genOpts)
	} else if hasProjectLayers {
		// Full local build + project layers
		genOpts.BaseDockerfile = generateBaseContent()
		dockerfile, err = GenerateDockerfile(genOpts)
	} else {
		// Full local build, no project layers — use cached if available
		if cached.Dockerfile != "" {
			dockerfile = cached.Dockerfile
		} else {
			dockerfile = GenerateBaseDockerfile()
		}
	}
	if err != nil {
		return fmt.Errorf("generating Dockerfile: %w", err)
	}

	tarBuf, err := buildContextTar(dockerfile, features, cached.Scripts)
	if err != nil {
		return fmt.Errorf("creating build context: %w", err)
	}

	return runBuild(ctx, cli, opts.ImageTag, tarBuf, opts.StreamOutput, opts.NoCache, opts.LogFn)
}

// tryPullBaseImage attempts to pull the GHCR base image.
// Returns true on success, false on failure.
func tryPullBaseImage(ctx context.Context, cli *client.Client, baseRef string) bool {
	pullCtx, cancel := context.WithTimeout(ctx, 60*time.Second)
	defer cancel()

	reader, err := cli.ImagePull(pullCtx, baseRef, image.PullOptions{})
	if err != nil {
		return false
	}
	defer reader.Close()

	// Consume pull output to completion.
	scanner := bufio.NewScanner(reader)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		var msg struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(scanner.Bytes(), &msg); err != nil {
			continue
		}
		if msg.Error != "" {
			return false
		}
	}
	if scanner.Err() != nil {
		return false
	}

	return true
}

// runBuild executes a Docker image build with the standard build args.
func runBuild(ctx context.Context, cli *client.Client, imageTag string, tarBuf *bytes.Buffer, streamOutput bool, noCache bool, logFn func(string)) error {
	buildArgs := map[string]*string{}

	tz := os.Getenv("TZ")
	if tz == "" {
		tz = "UTC"
	}
	buildArgs["TZ"] = &tz

	resp, err := cli.ImageBuild(ctx, tarBuf, types.ImageBuildOptions{
		Tags:       []string{imageTag},
		Dockerfile: "Dockerfile",
		BuildArgs:  buildArgs,
		Remove:     true,
		NoCache:    noCache,
	})
	if err != nil {
		return fmt.Errorf("starting image build: %w", err)
	}
	defer resp.Body.Close()

	scanner := bufio.NewScanner(resp.Body)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		var msg struct {
			Stream string `json:"stream"`
			Error  string `json:"error"`
		}
		if err := json.Unmarshal(scanner.Bytes(), &msg); err != nil {
			continue
		}
		if msg.Error != "" {
			return fmt.Errorf("build error: %s", msg.Error)
		}
		if msg.Stream != "" {
			if streamOutput {
				fmt.Print(msg.Stream)
			} else if logFn != nil && strings.HasPrefix(msg.Stream, "Step ") {
				logFn(strings.TrimSpace(msg.Stream))
			}
		}
	}
	if err := scanner.Err(); err != nil {
		return fmt.Errorf("reading build output: %w", err)
	}

	return nil
}

// ImageExists checks if the given image tag exists locally.
func ImageExists(ctx context.Context, cli *client.Client, imageTag string) bool {
	_, err := cli.ImageInspect(ctx, imageTag)
	return err == nil
}

// buildContextTar creates a tar archive from the Dockerfile, embedded scripts,
// and optional feature directories. When features is nil, only the base
// context (Dockerfile + scripts) is included. If cachedScripts is non-empty,
// those are used instead of calling BuildContextScripts().
func buildContextTar(dockerfile string, features []ResolvedFeature, cachedScripts []BuildContextFile) (*bytes.Buffer, error) {
	buf := new(bytes.Buffer)
	tw := tar.NewWriter(buf)

	// Use a fixed timestamp for reproducible builds / consistent Docker cache hits.
	modTime := reproducibleModTime

	if err := addTarEntry(tw, "Dockerfile", []byte(dockerfile), 0644, modTime); err != nil {
		return nil, fmt.Errorf("adding Dockerfile: %w", err)
	}
	scripts := cachedScripts
	if len(scripts) == 0 {
		scripts = BuildContextScripts()
	}
	for _, f := range scripts {
		if err := addTarEntry(tw, f.Name, f.Content, int64(f.Mode), modTime); err != nil {
			return nil, fmt.Errorf("adding %s: %w", f.Name, err)
		}
	}
	for _, f := range EgressProxySources() {
		if err := addTarEntry(tw, f.Name, f.Content, int64(f.Mode), modTime); err != nil {
			return nil, fmt.Errorf("adding %s: %w", f.Name, err)
		}
	}
	// Add feature directories under _features/<id>/
	for _, f := range features {
		featureBase := filepath.Clean(f.InstallDir)
		err := filepath.Walk(featureBase, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if info.IsDir() {
				return nil
			}

			relPath, err := filepath.Rel(featureBase, path)
			if err != nil {
				return err
			}
			relPath = filepath.ToSlash(relPath)

			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}

			tarPath := "_features/" + f.ID + "/" + relPath
			mode := int64(info.Mode().Perm())
			hdr := &tar.Header{
				Name:    tarPath,
				Mode:    mode,
				Size:    int64(len(data)),
				ModTime: modTime,
			}
			if err := tw.WriteHeader(hdr); err != nil {
				return err
			}
			if _, err := tw.Write(data); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return nil, fmt.Errorf("adding feature %s: %w", f.ID, err)
		}
	}

	if err := tw.Close(); err != nil {
		return nil, err
	}

	return buf, nil
}

// addTarEntry adds a single file entry to a tar writer.
func addTarEntry(tw *tar.Writer, name string, data []byte, mode int64, modTime time.Time) error {
	hdr := &tar.Header{
		Name:    name,
		Mode:    mode,
		Size:    int64(len(data)),
		ModTime: modTime,
	}
	if err := tw.WriteHeader(hdr); err != nil {
		return err
	}
	_, err := tw.Write(data)
	return err
}
