package container

import (
	"archive/tar"
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/image"
	"github.com/docker/docker/client"

	"github.com/Devon-White/claude-bunker/internal/config"
)

// reproducibleModTime is a fixed timestamp used for all build context tar
// entries to ensure reproducible builds and consistent Docker cache hits.
var reproducibleModTime = time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)

// BuildImage builds the Docker image entirely from in-memory and embedded content.
// No .devcontainer/ directory is needed — the Dockerfile is generated by Go,
// and scripts are embedded via go:embed.
//
// Uses --cache-from with the GHCR image (when version is set) to speed up
// builds without requiring a separate pull step.
// If streamOutput is true, full build output is streamed to stdout.
// Otherwise, only Step N/M progress lines are emitted via logFn.
func BuildImage(ctx context.Context, cli *client.Client, imageTag string, streamOutput bool, projectCfg config.ProjectConfig, version string, noCache bool, logFn func(string)) error {

	// Pull the GHCR image concurrently with build context preparation.
	// Skip cache pull when noCache is set (--rebuild).
	type pullResult struct{ cacheFrom []string }
	pullCh := make(chan pullResult, 1)
	baseRef := BaseImageRef(version)
	if baseRef != "" && !noCache {
		go func() {
			pullCh <- pullResult{tryCachePull(ctx, cli, baseRef)}
		}()
	} else {
		pullCh <- pullResult{}
	}

	baseDockerfile := GenerateBaseDockerfile()

	var tarBuf *bytes.Buffer
	var cleanupFn func()

	if projectCfg.HasGeneratedLayers() {
		features, cleanup, err := ResolveFeatures(projectCfg.Features)
		if err != nil {
			return fmt.Errorf("resolving features: %w", err)
		}
		cleanupFn = cleanup

		baseContent := generateBaseContent()
		merged, err := GenerateDockerfile(baseContent, features, projectCfg.Apt, projectCfg.Env)
		if err != nil {
			cleanupFn()
			return fmt.Errorf("generating Dockerfile: %w", err)
		}

		tarBuf, err = buildContextTar(merged, features)
		if err != nil {
			cleanupFn()
			return fmt.Errorf("creating build context: %w", err)
		}
	} else {
		var err error
		tarBuf, err = buildContextTar(baseDockerfile, nil)
		if err != nil {
			return fmt.Errorf("creating build context: %w", err)
		}
	}

	if cleanupFn != nil {
		defer cleanupFn()
	}

	// Collect cache pull result (blocks only if pull is still in progress).
	pr := <-pullCh
	return runBuild(ctx, cli, imageTag, tarBuf, streamOutput, pr.cacheFrom, noCache, logFn)
}

// tryCachePull attempts to pull the GHCR image for use as a build cache source.
// Returns the cache-from references on success, nil on failure.
func tryCachePull(ctx context.Context, cli *client.Client, baseRef string) []string {
	pullCtx, cancel := context.WithTimeout(ctx, 60*time.Second)
	defer cancel()

	reader, err := cli.ImagePull(pullCtx, baseRef, image.PullOptions{})
	if err != nil {
		return nil
	}
	defer reader.Close()

	// Consume pull output to completion.
	scanner := bufio.NewScanner(reader)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		var msg struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(scanner.Bytes(), &msg); err != nil {
			continue
		}
		if msg.Error != "" {
			return nil
		}
	}
	if scanner.Err() != nil {
		return nil
	}

	return []string{baseRef}
}

// runBuild executes a Docker image build with the standard build args.
func runBuild(ctx context.Context, cli *client.Client, imageTag string, tarBuf *bytes.Buffer, streamOutput bool, cacheFrom []string, noCache bool, logFn func(string)) error {
	buildArgs := map[string]*string{}

	tz := os.Getenv("TZ")
	if tz == "" {
		tz = "UTC"
	}
	buildArgs["TZ"] = &tz

	resp, err := cli.ImageBuild(ctx, tarBuf, types.ImageBuildOptions{
		Tags:       []string{imageTag},
		Dockerfile: "Dockerfile",
		BuildArgs:  buildArgs,
		Remove:     true,
		NoCache:    noCache,
		CacheFrom:  cacheFrom,
	})
	if err != nil {
		return fmt.Errorf("starting image build: %w", err)
	}
	defer resp.Body.Close()

	scanner := bufio.NewScanner(resp.Body)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		var msg struct {
			Stream string `json:"stream"`
			Error  string `json:"error"`
		}
		if err := json.Unmarshal(scanner.Bytes(), &msg); err != nil {
			continue
		}
		if msg.Error != "" {
			return fmt.Errorf("build error: %s", msg.Error)
		}
		if msg.Stream != "" {
			if streamOutput {
				fmt.Print(msg.Stream)
			} else if logFn != nil && strings.HasPrefix(msg.Stream, "Step ") {
				// Emit step progress in non-verbose mode
				logFn(strings.TrimSpace(msg.Stream))
			}
		}
	}
	if err := scanner.Err(); err != nil {
		return fmt.Errorf("reading build output: %w", err)
	}

	return nil
}

// ImageExists checks if the given image tag exists locally.
func ImageExists(ctx context.Context, cli *client.Client, imageTag string) bool {
	_, _, err := cli.ImageInspectWithRaw(ctx, imageTag)
	return err == nil
}

// buildContextTar creates a tar archive from the Dockerfile, embedded scripts,
// and optional feature directories. When features is nil, only the base
// context (Dockerfile + scripts) is included.
func buildContextTar(dockerfile string, features []ResolvedFeature) (*bytes.Buffer, error) {
	buf := new(bytes.Buffer)
	tw := tar.NewWriter(buf)

	// Use a fixed timestamp for reproducible builds / consistent Docker cache hits.
	modTime := reproducibleModTime

	if err := addTarEntry(tw, "Dockerfile", []byte(dockerfile), 0644, modTime); err != nil {
		return nil, fmt.Errorf("adding Dockerfile: %w", err)
	}
	if err := addTarEntry(tw, "init-firewall.sh", InitFirewallScript(), 0755, modTime); err != nil {
		return nil, fmt.Errorf("adding init-firewall.sh: %w", err)
	}
	if err := addTarEntry(tw, "tmux.conf", TmuxConf(), 0644, modTime); err != nil {
		return nil, fmt.Errorf("adding tmux.conf: %w", err)
	}
	// Add feature directories under _features/<id>/
	for _, f := range features {
		featureBase := filepath.Clean(f.InstallDir)
		err := filepath.Walk(featureBase, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if info.IsDir() {
				return nil
			}

			relPath, err := filepath.Rel(featureBase, path)
			if err != nil {
				return err
			}
			relPath = strings.ReplaceAll(relPath, "\\", "/")

			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}

			tarPath := "_features/" + f.ID + "/" + relPath
			mode := int64(info.Mode().Perm())
			hdr := &tar.Header{
				Name:    tarPath,
				Mode:    mode,
				Size:    int64(len(data)),
				ModTime: modTime,
			}
			if err := tw.WriteHeader(hdr); err != nil {
				return err
			}
			if _, err := tw.Write(data); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return nil, fmt.Errorf("adding feature %s: %w", f.ID, err)
		}
	}

	if err := tw.Close(); err != nil {
		return nil, err
	}

	return buf, nil
}

// addTarEntry adds a single file entry to a tar writer.
func addTarEntry(tw *tar.Writer, name string, data []byte, mode int64, modTime time.Time) error {
	hdr := &tar.Header{
		Name:    name,
		Mode:    mode,
		Size:    int64(len(data)),
		ModTime: modTime,
	}
	if err := tw.WriteHeader(hdr); err != nil {
		return err
	}
	_, err := tw.Write(data)
	return err
}
