package devcontainer

import (
	"encoding/json"
	"strings"

	"github.com/Devon-White/claude-bunker/internal/config"
	bunkerlog "github.com/Devon-White/claude-bunker/internal/log"
)

// GeneratedMarker is the first line of a bunker-generated devcontainer.json.
// Its presence marks the file as bunker-owned (regenerated wholesale).
const GeneratedMarker = "// GENERATED by claude-bunker — do not edit"

// GenerateOpts carries values Generate needs beyond ProjectConfig.
type GenerateOpts struct {
	Name              string
	Image             string
	ClaudeCodeFeature string // OCI ref for the claude-code feature; "" to omit
	FirewallFeature   string // OCI ref for the firewall feature; "" to omit
	HardeningFeature  string // OCI ref for the hardening feature; "" to omit
}

// seccompRunArgs is the docker runArgs pair that applies the portable
// .devcontainer/seccomp.json (see container.SeccompProfileJSON, the single
// source of truth also used for bunker's native container creation) via
// VS Code / Codespaces.
//
// runArgs entries are opaque Docker CLI args: the devcontainer CLI does NOT
// resolve relative paths inside them against the devcontainer.json folder —
// it substitutes known ${...} variables textually, then execs `docker run`
// from its own process cwd (not necessarily the workspace). A bare relative
// path like "./.devcontainer/seccomp.json" is a known footgun (see
// devcontainers/cli#210, devcontainers/features#207 — relative seccomp paths
// don't resolve). ${localWorkspaceFolder} is the spec-documented substitution
// for exactly this case (mirrors the spec's own
// `--env-file ${localWorkspaceFolder}/.devcontainer/.env` example) and
// expands to an absolute host path before docker ever sees the arg.
var seccompRunArgs = []string{"--security-opt", "seccomp=${localWorkspaceFolder}/.devcontainer/seccomp.json"}

// isEnvRef reports whether s is an environment-variable reference (${VAR} or $VAR)
// rather than a literal value. Literal secrets must not be written to the
// committed devcontainer.json.
func isEnvRef(s string) bool {
	return strings.Contains(s, "${") || strings.HasPrefix(s, "$")
}

// Generate produces a spec-conformant devcontainer.json (prefixed with the
// GENERATED marker) from a ProjectConfig. Security-critical fields are forced:
// capAdd gets NET_ADMIN/NET_RAW, remoteUser is claude-bunker. Bunker extras go
// in customizations["claude-bunker"].
func Generate(cfg config.ProjectConfig, opts GenerateOpts) ([]byte, error) {
	features := map[string]any{}
	if opts.ClaudeCodeFeature != "" {
		features[opts.ClaudeCodeFeature] = map[string]any{}
	}
	if opts.FirewallFeature != "" {
		fw := map[string]any{}
		if len(cfg.AllowDomains) > 0 {
			fw["allowDomains"] = strings.Join(cfg.AllowDomains, ",")
		}
		features[opts.FirewallFeature] = fw
	}
	if opts.HardeningFeature != "" {
		features[opts.HardeningFeature] = map[string]any{}
	}
	for ref, o := range cfg.Features {
		features[ref] = o
	}

	dc := map[string]any{
		"capAdd":     forcedCaps,
		"remoteUser": bunkerUser,
		"runArgs":    seccompRunArgs,
	}
	if opts.Name != "" {
		dc["name"] = opts.Name
	}
	if opts.Image != "" {
		dc["image"] = opts.Image
	}
	if len(features) > 0 {
		dc["features"] = features
	}
	if len(cfg.Env) > 0 {
		dc["containerEnv"] = cfg.Env
	}
	if cfg.PostStartCommand != "" {
		dc["postStartCommand"] = cfg.PostStartCommand
	}
	if cfg.OnCreateCommand != "" {
		dc["onCreateCommand"] = cfg.OnCreateCommand
	}

	bc := map[string]any{}
	if len(cfg.Exclude) > 0 {
		bc["exclude"] = cfg.Exclude
	}
	if len(cfg.AllowDomains) > 0 {
		bc["allowDomains"] = cfg.AllowDomains
	}
	if cfg.Plugins != "" {
		bc["plugins"] = cfg.Plugins
	}
	if cfg.GhToken != "" {
		if isEnvRef(cfg.GhToken) {
			bc["ghToken"] = cfg.GhToken
		} else {
			bunkerlog.Warn("ghToken looks like a literal secret; omitting it from devcontainer.json. Pass it via --gh-token or the $GH_TOKEN env var, or use a \"${GH_TOKEN}\" reference.")
		}
	}
	if cfg.SeedHistory != nil {
		bc["seedHistory"] = *cfg.SeedHistory
	}
	if cfg.Workspace != "" {
		bc["workspace"] = cfg.Workspace
	}
	if len(bc) > 0 {
		dc["customizations"] = map[string]any{bunkerCustomizationsKey: bc}
	}

	body, err := json.MarshalIndent(dc, "", "  ")
	if err != nil {
		return nil, err
	}
	out := []byte(GeneratedMarker + "\n")
	out = append(out, body...)
	out = append(out, '\n')
	return out, nil
}
