package devcontainer

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/Devon-White/claude-bunker/internal/config"
	"github.com/Devon-White/claude-bunker/internal/container"
	bunkerlog "github.com/Devon-White/claude-bunker/internal/log"
)

// GeneratedMarker is the first line of a bunker-generated devcontainer.json.
// Its presence marks the file as bunker-owned (regenerated wholesale).
const GeneratedMarker = "// GENERATED by claude-bunker — do not edit"

// GenerateOpts carries values Generate needs beyond ProjectConfig.
type GenerateOpts struct {
	Name string
}

// seccompRunArgs is the docker runArgs pair that applies the portable
// .devcontainer/seccomp.json (see container.SeccompProfileJSON, the single
// source of truth also used for bunker's native container creation) via
// VS Code / Codespaces.
//
// runArgs entries are opaque Docker CLI args: the devcontainer CLI does NOT
// resolve relative paths inside them against the devcontainer.json folder —
// it substitutes known ${...} variables textually, then execs `docker run`
// from its own process cwd (not necessarily the workspace). A bare relative
// path like "./.devcontainer/seccomp.json" is a known footgun (see
// devcontainers/cli#210, devcontainers/features#207 — relative seccomp paths
// don't resolve). ${localWorkspaceFolder} is the spec-documented substitution
// for exactly this case (mirrors the spec's own
// `--env-file ${localWorkspaceFolder}/.devcontainer/.env` example) and
// expands to an absolute host path before docker ever sees the arg.
var seccompRunArgs = []string{"--security-opt", "seccomp=${localWorkspaceFolder}/.devcontainer/seccomp.json"}

// isEnvRef reports whether s is an environment-variable reference (${VAR} or $VAR)
// rather than a literal value. Literal secrets must not be written to the
// committed devcontainer.json.
func isEnvRef(s string) bool {
	return strings.Contains(s, "${") || strings.HasPrefix(s, "$")
}

// firewallPostStartCommand is the postStartCommand Generate emits for the
// portable (VS Code / Codespaces) build path: it sudo-runs the firewall (and
// then backgrounds the refresh daemon) against the BAKED, root-owned
// allowlist path (container.AllowedDomainsPath) — never a workspace-writable
// copy, since a sandboxed agent could widen that to escape the firewall.
// This exact command (script path + domains path) must match the arg-pinned
// sudoers grant baked into base.dockerfile.tmpl, or sudo denies it.
//
// The backgrounded refresh is wrapped in a subshell — "(sudo ... &)" — rather
// than backgrounded at the top level. A trailing top-level "&" would make
// this the last word of the *whole* postStartCommand once Generate appends
// " && " + a user's own postStartCommand, producing "... & && npm install":
// a shell syntax error (`&&` with no left-hand command), which aborts the
// entire postStartCommand under the devcontainer CLI's `/bin/sh -c` — the
// firewall never comes up AND the user's command never runs. The subshell
// still backgrounds the refresh daemon (it returns immediately), but the
// command as a whole now ends in ")", so it chains cleanly with " && ".
//
// Bunker's own native build/run never uses this string — it runs the
// firewall directly as root via docker exec (internal/container/lifecycle.go)
// and the baked allowlist path isn't even present in bunker's native image
// (only the portable Dockerfile COPYs it in, see cmd/init.go's
// writeDevContainer). LoadProjectConfig strips this string back out of
// PostStartCommand (see stripBunkerPostStart in load.go) so bunker's own
// postStart step doesn't try to re-run it against a nonexistent file.
func firewallPostStartCommand() string {
	return fmt.Sprintf("sudo %s %s && (sudo %s %s >/dev/null 2>&1 &)",
		container.FirewallScriptPath, container.AllowedDomainsPath,
		container.RefreshFirewallScriptPath, container.AllowedDomainsPath)
}

// Generate produces a spec-conformant devcontainer.json (prefixed with the
// GENERATED marker) from a ProjectConfig. Security-critical fields are forced:
// capAdd gets NET_ADMIN/NET_RAW, remoteUser is claude-bunker, build.dockerfile
// points VS Code/Codespaces at the sibling committed Dockerfile (which bakes
// in the firewall/hardening and installs Claude Code natively — no OCI
// Feature refs needed for any of that). Bunker extras go in
// customizations["claude-bunker"].
func Generate(cfg config.ProjectConfig, opts GenerateOpts) ([]byte, error) {
	features := map[string]any{}
	for ref, o := range cfg.Features {
		features[ref] = o
	}

	dc := map[string]any{
		"build":      map[string]any{"dockerfile": "Dockerfile"},
		"capAdd":     forcedCaps,
		"remoteUser": bunkerUser,
		"runArgs":    seccompRunArgs,
	}
	if opts.Name != "" {
		dc["name"] = opts.Name
	}
	if len(features) > 0 {
		dc["features"] = features
	}
	if len(cfg.Env) > 0 {
		dc["containerEnv"] = cfg.Env
	}
	// The firewall must be up before anything else touches the network, so
	// it always runs first; a user's own postStartCommand (if any) runs
	// after it.
	firewallCmd := firewallPostStartCommand()
	if cfg.PostStartCommand != "" {
		dc["postStartCommand"] = firewallCmd + " && " + cfg.PostStartCommand
	} else {
		dc["postStartCommand"] = firewallCmd
	}
	if cfg.OnCreateCommand != "" {
		dc["onCreateCommand"] = cfg.OnCreateCommand
	}

	bc := map[string]any{}
	if len(cfg.Exclude) > 0 {
		bc["exclude"] = cfg.Exclude
	}
	if len(cfg.AllowDomains) > 0 {
		bc["allowDomains"] = cfg.AllowDomains
	}
	if cfg.Plugins != "" {
		bc["plugins"] = cfg.Plugins
	}
	if cfg.GhToken != "" {
		if isEnvRef(cfg.GhToken) {
			bc["ghToken"] = cfg.GhToken
		} else {
			bunkerlog.Warn("ghToken looks like a literal secret; omitting it from devcontainer.json. Pass it via --gh-token or the $GH_TOKEN env var, or use a \"${GH_TOKEN}\" reference.")
		}
	}
	if cfg.SeedHistory != nil {
		bc["seedHistory"] = *cfg.SeedHistory
	}
	if cfg.Workspace != "" {
		bc["workspace"] = cfg.Workspace
	}
	if len(bc) > 0 {
		dc["customizations"] = map[string]any{bunkerCustomizationsKey: bc}
	}

	body, err := json.MarshalIndent(dc, "", "  ")
	if err != nil {
		return nil, err
	}
	out := []byte(GeneratedMarker + "\n")
	out = append(out, body...)
	out = append(out, '\n')
	return out, nil
}
