package devcontainer

import (
	"encoding/json"

	"github.com/Devon-White/claude-bunker/internal/config"
)

// GeneratedMarker is the first line of a bunker-generated devcontainer.json.
// Its presence marks the file as bunker-owned (regenerated wholesale).
const GeneratedMarker = "// GENERATED by claude-bunker — do not edit"

// GenerateOpts carries values Generate needs beyond ProjectConfig.
type GenerateOpts struct {
	Name              string
	Image             string
	ClaudeCodeFeature string // OCI ref for the claude-code feature; "" to omit
}

// Generate produces a spec-conformant devcontainer.json (prefixed with the
// GENERATED marker) from a ProjectConfig. Security-critical fields are forced:
// capAdd gets NET_ADMIN/NET_RAW, remoteUser is claude-bunker. Bunker extras go
// in customizations["claude-bunker"].
func Generate(cfg config.ProjectConfig, opts GenerateOpts) ([]byte, error) {
	features := map[string]interface{}{}
	if opts.ClaudeCodeFeature != "" {
		features[opts.ClaudeCodeFeature] = map[string]interface{}{}
	}
	for ref, o := range cfg.Features {
		features[ref] = o
	}

	dc := map[string]interface{}{
		"capAdd":     forcedCaps,
		"remoteUser": bunkerUser,
	}
	if opts.Name != "" {
		dc["name"] = opts.Name
	}
	if opts.Image != "" {
		dc["image"] = opts.Image
	}
	if len(features) > 0 {
		dc["features"] = features
	}
	if len(cfg.Env) > 0 {
		dc["containerEnv"] = cfg.Env
	}
	if cfg.PostStartCommand != "" {
		dc["postStartCommand"] = cfg.PostStartCommand
	}
	if cfg.OnCreateCommand != "" {
		dc["onCreateCommand"] = cfg.OnCreateCommand
	}

	bc := map[string]interface{}{}
	if len(cfg.Exclude) > 0 {
		bc["exclude"] = cfg.Exclude
	}
	if len(cfg.AllowDomains) > 0 {
		bc["allowDomains"] = cfg.AllowDomains
	}
	if len(cfg.Apt) > 0 {
		bc["apt"] = cfg.Apt
	}
	if cfg.Plugins != "" {
		bc["plugins"] = cfg.Plugins
	}
	if cfg.GhToken != "" {
		bc["ghToken"] = cfg.GhToken
	}
	if cfg.SeedHistory != nil {
		bc["seedHistory"] = *cfg.SeedHistory
	}
	if cfg.Workspace != "" {
		bc["workspace"] = cfg.Workspace
	}
	if len(bc) > 0 {
		dc["customizations"] = map[string]interface{}{bunkerCustomizationsKey: bc}
	}

	body, err := json.MarshalIndent(dc, "", "  ")
	if err != nil {
		return nil, err
	}
	out := []byte(GeneratedMarker + "\n")
	out = append(out, body...)
	out = append(out, '\n')
	return out, nil
}
