package cmd

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/charmbracelet/huh"

	"github.com/Devon-White/claude-bunker/internal/config"
	"github.com/Devon-White/claude-bunker/internal/devcontainer"
)

func TestNonInteractiveInit(t *testing.T) {
	// Without --defaults, init must refuse (no write) and return an error.
	write, err := nonInteractiveInit(false)
	if err == nil {
		t.Error("expected an error when not a TTY and --defaults not given")
	}
	if write {
		t.Error("must not write a config when refusing")
	}
	// With --defaults, init writes.
	write, err = nonInteractiveInit(true)
	if err != nil {
		t.Errorf("--defaults should not error, got %v", err)
	}
	if !write {
		t.Error("--defaults should write a config")
	}
}

func TestAbortErr(t *testing.T) {
	if got := abortErr(huh.ErrUserAborted); ExitCodeFor(got) != ExitCancelled {
		t.Errorf("user abort should map to ExitCancelled, got code %d", ExitCodeFor(got))
	}
	other := errors.New("form failed")
	if got := abortErr(other); !errors.Is(got, other) {
		t.Errorf("non-abort error should pass through, got %v", got)
	}
}

func TestRunInit_NonTTYWithoutDefaultsLeavesFileUntouched(t *testing.T) {
	ws := t.TempDir()
	t.Setenv("CLAUDE_BUNKER_WS", ws)

	cfgPath := devcontainer.DevContainerPath(ws)
	if err := os.MkdirAll(filepath.Dir(cfgPath), 0o755); err != nil {
		t.Fatal(err)
	}
	original := []byte(`{"customizations":{"claude-bunker":{"apt":["ripgrep"]}}}` + "\n")
	if err := os.WriteFile(cfgPath, original, 0o644); err != nil {
		t.Fatal(err)
	}

	// Force the non-interactive path.
	orig := stdinIsTTY
	stdinIsTTY = func() bool { return false }
	t.Cleanup(func() { stdinIsTTY = orig })

	err := runInit(initCmd, nil)
	if err == nil {
		t.Fatal("expected runInit to error on non-TTY without --defaults")
	}

	got, readErr := os.ReadFile(cfgPath)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if string(got) != string(original) {
		t.Errorf("config was modified: got %q, want %q", got, original)
	}
}

func TestWriteDevContainer(t *testing.T) {
	ws := t.TempDir()
	seed := false
	cfg := config.ProjectConfig{
		Features:    map[string]map[string]any{"ghcr.io/devcontainers/features/node:1": {"version": "20"}},
		Exclude:     []string{"secrets/"},
		SeedHistory: &seed,
	}
	if err := writeDevContainer(ws, cfg); err != nil {
		t.Fatalf("writeDevContainer: %v", err)
	}
	p := filepath.Join(ws, ".devcontainer", "devcontainer.json")
	data, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("generated file missing: %v", err)
	}
	if !bytes.HasPrefix(bytes.TrimLeft(data, "\n"), []byte("// GENERATED by claude-bunker")) {
		t.Error("generated file must start with the GENERATED marker")
	}
	// Round-trips back to the engine config with the user feature (claude-code stripped).
	loaded, found, err := devcontainer.LoadProjectConfig(ws)
	if err != nil || !found {
		t.Fatalf("round-trip load: found=%v err=%v", found, err)
	}
	if _, ok := loaded.Features["ghcr.io/devcontainers/features/node:1"]; !ok {
		t.Error("user feature lost in generate→load round-trip")
	}
	if len(loaded.Exclude) != 1 {
		t.Errorf("exclude lost: %+v", loaded.Exclude)
	}
	if _, ok := loaded.Features["ghcr.io/anthropics/devcontainer-features/claude-code:1"]; ok {
		t.Error("claude-code feature must be stripped from the engine config on load")
	}
}

func TestWriteDevContainer_DryRunPlansWithoutWriting(t *testing.T) {
	ws := t.TempDir()

	var buf bytes.Buffer
	origErr := errW
	errW = &buf
	t.Cleanup(func() { errW = origErr })

	origDry := dryRun
	dryRun = true
	t.Cleanup(func() { dryRun = origDry })

	cfg := config.ProjectConfig{
		Features: map[string]map[string]any{
			"ghcr.io/devcontainers/features/node:1": {"version": "20"},
		},
	}
	if err := writeDevContainer(ws, cfg); err != nil {
		t.Fatalf("writeDevContainer: %v", err)
	}

	p := devcontainer.DevContainerPath(ws)
	if _, err := os.Stat(p); !os.IsNotExist(err) {
		t.Fatalf("dry-run must not create %s (stat err = %v)", p, err)
	}
	if _, err := os.Stat(filepath.Dir(p)); !os.IsNotExist(err) {
		t.Errorf("dry-run must not create the .devcontainer directory")
	}
	if !strings.Contains(buf.String(), "would write "+p) {
		t.Errorf("plan output missing %q; got %q", "would write "+p, buf.String())
	}
}

// TestLoadConfig_ExpandsGhTokenBeforeAuth locks the ordering of the single
// riskiest line in loadConfig: config.ExpandProjectConfig(&cfg) must run
// before auth resolution reads GhToken, otherwise a raw ${VAR} reference
// would leak into the container instead of its resolved value.
func TestLoadConfig_ExpandsGhTokenBeforeAuth(t *testing.T) {
	ws := t.TempDir()
	dir := filepath.Join(ws, ".devcontainer")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	body := `{"customizations":{"claude-bunker":{"ghToken":"${CB_TEST_GH_TOKEN}"}}}`
	if err := os.WriteFile(filepath.Join(dir, "devcontainer.json"), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Setenv("CB_TEST_GH_TOKEN", "resolved-token-value")

	r := &runner{workspace: ws}
	r.loadConfig(bunkerFlags{})
	if r.projectCfg.GhToken != "resolved-token-value" {
		t.Errorf("ghToken not expanded in projectCfg: %q", r.projectCfg.GhToken)
	}
	if r.auth.GhToken != "resolved-token-value" {
		t.Errorf("auth.GhToken must be the EXPANDED token (expand must run before auth resolution): %q", r.auth.GhToken)
	}
}
