package cmd

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/charmbracelet/huh"

	"github.com/Devon-White/claude-bunker/internal/config"
	"github.com/Devon-White/claude-bunker/internal/container"
	"github.com/Devon-White/claude-bunker/internal/devcontainer"
)

func TestNonInteractiveInit(t *testing.T) {
	// Without --defaults, init must refuse (no write) and return an error.
	write, err := nonInteractiveInit(false)
	if err == nil {
		t.Error("expected an error when not a TTY and --defaults not given")
	}
	if write {
		t.Error("must not write a config when refusing")
	}
	// With --defaults, init writes.
	write, err = nonInteractiveInit(true)
	if err != nil {
		t.Errorf("--defaults should not error, got %v", err)
	}
	if !write {
		t.Error("--defaults should write a config")
	}
}

func TestAbortErr(t *testing.T) {
	if got := abortErr(huh.ErrUserAborted); ExitCodeFor(got) != ExitCancelled {
		t.Errorf("user abort should map to ExitCancelled, got code %d", ExitCodeFor(got))
	}
	other := errors.New("form failed")
	if got := abortErr(other); !errors.Is(got, other) {
		t.Errorf("non-abort error should pass through, got %v", got)
	}
}

func TestRunInit_NonTTYWithoutDefaultsLeavesFileUntouched(t *testing.T) {
	ws := t.TempDir()
	t.Setenv("CLAUDE_BUNKER_WS", ws)

	cfgPath := devcontainer.DevContainerPath(ws)
	if err := os.MkdirAll(filepath.Dir(cfgPath), 0o755); err != nil {
		t.Fatal(err)
	}
	original := []byte(`{"customizations":{"claude-bunker":{"plugins":"project"}}}` + "\n")
	if err := os.WriteFile(cfgPath, original, 0o644); err != nil {
		t.Fatal(err)
	}

	// Force the non-interactive path.
	orig := stdinIsTTY
	stdinIsTTY = func() bool { return false }
	t.Cleanup(func() { stdinIsTTY = orig })

	err := runInit(initCmd, nil)
	if err == nil {
		t.Fatal("expected runInit to error on non-TTY without --defaults")
	}

	got, readErr := os.ReadFile(cfgPath)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if string(got) != string(original) {
		t.Errorf("config was modified: got %q, want %q", got, original)
	}
}

func TestWriteDevContainer(t *testing.T) {
	ws := t.TempDir()
	seed := false
	cfg := config.ProjectConfig{
		Features:    map[string]map[string]any{"ghcr.io/devcontainers/features/node:1": {"version": "20"}},
		Exclude:     []string{"secrets/"},
		SeedHistory: &seed,
	}
	if err := writeDevContainer(ws, cfg); err != nil {
		t.Fatalf("writeDevContainer: %v", err)
	}
	p := filepath.Join(ws, ".devcontainer", "devcontainer.json")
	data, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("generated file missing: %v", err)
	}
	if !bytes.HasPrefix(bytes.TrimLeft(data, "\n"), []byte("// GENERATED by claude-bunker")) {
		t.Error("generated file must start with the GENERATED marker")
	}
	// Round-trips back to the engine config with the user feature (claude-code stripped).
	loaded, found, err := devcontainer.LoadProjectConfig(ws)
	if err != nil || !found {
		t.Fatalf("round-trip load: found=%v err=%v", found, err)
	}
	if _, ok := loaded.Features["ghcr.io/devcontainers/features/node:1"]; !ok {
		t.Error("user feature lost in generate→load round-trip")
	}
	if len(loaded.Exclude) != 1 {
		t.Errorf("exclude lost: %+v", loaded.Exclude)
	}
	if _, ok := loaded.Features["ghcr.io/anthropics/devcontainer-features/claude-code:1"]; ok {
		t.Error("claude-code feature must be stripped from the engine config on load")
	}
	if _, ok := loaded.Features["ghcr.io/Devon-White/claude-bunker/firewall:0"]; ok {
		t.Error("firewall feature must be stripped from the engine config on load")
	}
	if _, ok := loaded.Features["ghcr.io/Devon-White/claude-bunker/hardening:0"]; ok {
		t.Error("hardening feature must be stripped from the engine config on load")
	}
}

// TestWriteDevContainer_WritesSeccompProfile locks in VS Code portability: a
// sibling .devcontainer/seccomp.json must be written alongside
// devcontainer.json, sourced from container.SeccompProfileJSON() (the single
// source of truth also used for bunker's native container creation) — never
// a hardcoded/duplicated profile.
func TestWriteDevContainer_WritesSeccompProfile(t *testing.T) {
	ws := t.TempDir()
	if err := writeDevContainer(ws, config.ProjectConfig{}); err != nil {
		t.Fatalf("writeDevContainer: %v", err)
	}
	p := filepath.Join(ws, ".devcontainer", "seccomp.json")
	data, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("seccomp.json missing: %v", err)
	}
	if string(data) != container.SeccompProfileJSON() {
		t.Errorf("seccomp.json content diverges from container.SeccompProfileJSON()")
	}

	// The devcontainer.json must reference the seccomp.json via runArgs, build
	// from the sibling Dockerfile (no OCI hardening Feature refs — the
	// Dockerfile does that natively), and bootstrap the firewall via
	// postStartCommand against the baked allowlist path.
	dcData, err := os.ReadFile(filepath.Join(ws, ".devcontainer", "devcontainer.json"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(dcData, []byte("seccomp=${localWorkspaceFolder}/.devcontainer/seccomp.json")) {
		t.Error("devcontainer.json missing runArgs seccomp reference")
	}
	if !bytes.Contains(dcData, []byte(`"dockerfile": "Dockerfile"`)) {
		t.Error("devcontainer.json missing build.dockerfile")
	}
	if bytes.Contains(dcData, []byte("ghcr.io/Devon-White/claude-bunker/firewall")) {
		t.Error("devcontainer.json must not reference the firewall OCI feature (baked into the Dockerfile instead)")
	}
	if bytes.Contains(dcData, []byte("ghcr.io/Devon-White/claude-bunker/hardening")) {
		t.Error("devcontainer.json must not reference the hardening OCI feature (baked into the Dockerfile instead)")
	}
	if !bytes.Contains(dcData, []byte("sudo "+container.FirewallScriptPath+" "+container.AllowedDomainsPath)) {
		t.Error("devcontainer.json missing firewall postStartCommand against the baked allowlist")
	}
}

// TestWriteDevContainer_WritesDockerfile locks in the VS Code portability
// path: a sibling .devcontainer/Dockerfile must be written, built from
// container.GenerateBaseDockerfile() (the same base bunker's native build
// uses) plus a suffix that COPYs the allowlist and locks it down root-owned
// + read-only, so a sandboxed agent cannot widen the firewall's allowlist.
func TestWriteDevContainer_WritesDockerfile(t *testing.T) {
	ws := t.TempDir()
	if err := writeDevContainer(ws, config.ProjectConfig{}); err != nil {
		t.Fatalf("writeDevContainer: %v", err)
	}
	p := filepath.Join(ws, ".devcontainer", "Dockerfile")
	data, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("Dockerfile missing: %v", err)
	}
	if !strings.HasPrefix(string(data), container.GenerateBaseDockerfile()) {
		t.Error("Dockerfile must start with container.GenerateBaseDockerfile()")
	}
	wantCopy := "COPY allowed-domains.txt " + container.AllowedDomainsPath
	if !strings.Contains(string(data), wantCopy) {
		t.Errorf("Dockerfile missing %q", wantCopy)
	}
	wantChmod := "chmod 0444 " + container.AllowedDomainsPath
	if !strings.Contains(string(data), wantChmod) {
		t.Errorf("Dockerfile missing %q", wantChmod)
	}
	// The suffix must switch back to the non-root user after the chmod so
	// the committed Dockerfile doesn't end the image on USER root.
	trimmed := strings.TrimRight(string(data), "\n")
	wantTail := "USER " + container.ContainerUser
	if !strings.HasSuffix(trimmed, wantTail) {
		t.Errorf("Dockerfile must end with %q, got tail %q", wantTail, trimmed[max(0, len(trimmed)-40):])
	}
}

// TestWriteDevContainer_BakesEgressProxy locks in Tier-1 protection for the
// portable (VS Code/Codespaces) path: the committed Dockerfile must build the
// multi-stage egress proxy, and the egressproxy/ source it COPYs must actually
// be written into the bundle so that COPY resolves. No masking config is
// written here — portable is Tier 1 (splice/allowlist) only.
func TestWriteDevContainer_BakesEgressProxy(t *testing.T) {
	ws := t.TempDir()
	if err := writeDevContainer(ws, config.ProjectConfig{}); err != nil {
		t.Fatalf("writeDevContainer: %v", err)
	}

	df, err := os.ReadFile(filepath.Join(ws, ".devcontainer", "Dockerfile"))
	if err != nil {
		t.Fatalf("Dockerfile missing: %v", err)
	}
	if !strings.Contains(string(df), "AS proxybuild") || !strings.Contains(string(df), "COPY egressproxy/") {
		t.Error("committed Dockerfile does not build the egress proxy")
	}

	if _, err := os.Stat(filepath.Join(ws, ".devcontainer", "egressproxy", "main.go")); err != nil {
		t.Errorf("egressproxy/main.go not written into bundle: %v", err)
	}
	if _, err := os.Stat(filepath.Join(ws, ".devcontainer", "egressproxy", "go.mod")); err != nil {
		t.Errorf("egressproxy/go.mod not written into bundle: %v", err)
	}

	// No masking config in the portable bundle (Tier 1 only).
	if _, err := os.Stat(filepath.Join(ws, ".devcontainer", "masking.json")); !os.IsNotExist(err) {
		t.Errorf("portable bundle must not include masking.json, stat err = %v", err)
	}
}

// TestWriteDevContainer_WritesFirewallScripts locks in that the 3 firewall
// scripts written alongside the Dockerfile are byte-identical to bunker's
// canonical container.BuildContextScripts() entries (no drift/copy-paste),
// so the Dockerfile's COPY steps for them resolve.
func TestWriteDevContainer_WritesFirewallScripts(t *testing.T) {
	ws := t.TempDir()
	if err := writeDevContainer(ws, config.ProjectConfig{}); err != nil {
		t.Fatalf("writeDevContainer: %v", err)
	}
	canonical := make(map[string][]byte)
	for _, f := range container.BuildContextScripts() {
		canonical[f.Name] = f.Content
	}
	for _, name := range []string{"init-firewall.sh", "refresh-firewall.sh", "firewall-common.sh"} {
		want, ok := canonical[name]
		if !ok {
			t.Fatalf("canonical BuildContextScripts() missing %s", name)
		}
		got, err := os.ReadFile(filepath.Join(ws, ".devcontainer", name))
		if err != nil {
			t.Fatalf("%s missing: %v", name, err)
		}
		if !bytes.Equal(got, want) {
			t.Errorf("%s content diverges from container.BuildContextScripts()", name)
		}
	}
}

// TestWriteDevContainer_WritesAllowedDomains locks in that allowed-domains.txt
// is derived from container.BuiltinDomains() (with no project AllowDomains,
// it is exactly the builtins joined by newlines) — the file baked root-owned
// into the Dockerfile.
func TestWriteDevContainer_WritesAllowedDomains(t *testing.T) {
	ws := t.TempDir()
	if err := writeDevContainer(ws, config.ProjectConfig{}); err != nil {
		t.Fatalf("writeDevContainer: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(ws, ".devcontainer", "allowed-domains.txt"))
	if err != nil {
		t.Fatalf("allowed-domains.txt missing: %v", err)
	}
	want := strings.Join(container.BuiltinDomains(), "\n") + "\n"
	if string(data) != want {
		t.Errorf("allowed-domains.txt = %q, want %q", data, want)
	}
}

// TestWriteDevContainer_AllowedDomainsIncludesExtraDomains verifies the
// project's extra allowDomains are appended after the builtins.
func TestWriteDevContainer_AllowedDomainsIncludesExtraDomains(t *testing.T) {
	ws := t.TempDir()
	cfg := config.ProjectConfig{AllowDomains: []string{"registry.npmjs.org", "pypi.org"}}
	if err := writeDevContainer(ws, cfg); err != nil {
		t.Fatalf("writeDevContainer: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(ws, ".devcontainer", "allowed-domains.txt"))
	if err != nil {
		t.Fatalf("allowed-domains.txt missing: %v", err)
	}
	want := strings.Join(append(container.BuiltinDomains(), "registry.npmjs.org", "pypi.org"), "\n") + "\n"
	if string(data) != want {
		t.Errorf("allowed-domains.txt = %q, want %q", data, want)
	}
}

func TestWriteDevContainer_DryRunPlansWithoutWriting(t *testing.T) {
	ws := t.TempDir()

	var buf bytes.Buffer
	origErr := errW
	errW = &buf
	t.Cleanup(func() { errW = origErr })

	origDry := dryRun
	dryRun = true
	t.Cleanup(func() { dryRun = origDry })

	cfg := config.ProjectConfig{
		Features: map[string]map[string]any{
			"ghcr.io/devcontainers/features/node:1": {"version": "20"},
		},
	}
	if err := writeDevContainer(ws, cfg); err != nil {
		t.Fatalf("writeDevContainer: %v", err)
	}

	p := devcontainer.DevContainerPath(ws)
	if _, err := os.Stat(p); !os.IsNotExist(err) {
		t.Fatalf("dry-run must not create %s (stat err = %v)", p, err)
	}
	if _, err := os.Stat(filepath.Dir(p)); !os.IsNotExist(err) {
		t.Errorf("dry-run must not create the .devcontainer directory")
	}
	if !strings.Contains(buf.String(), "would write "+p) {
		t.Errorf("plan output missing %q; got %q", "would write "+p, buf.String())
	}
}

// TestMergeSettings_AptPackagesBecomeStandardFeature locks in the portability
// fix: the wizard must express extra apt packages via the standard
// apt-packages devcontainer feature (which VS Code/Codespaces and bunker both
// resolve), not the old bunker-specific "apt" field (which only claude-bunker
// ever read — customizations namespaces are ignored by the VS Code path).
func TestMergeSettings_AptPackagesBecomeStandardFeature(t *testing.T) {
	cfg := map[string]any{}
	s := initSettings{aptPackages: "jq ripgrep"}
	mergeSettings(cfg, s)

	feats, ok := cfg["features"].(map[string]any)
	if !ok {
		t.Fatalf("expected a features map; cfg=%v", cfg)
	}
	entry, ok := feats[aptPackagesFeatureRef]
	if !ok {
		t.Fatalf("expected apt-packages feature entry; features=%v", feats)
	}
	opts, ok := entry.(map[string]any)
	if !ok {
		t.Fatalf("feature entry must be a map, got %T", entry)
	}
	if got := opts["packages"]; got != "jq,ripgrep" {
		t.Errorf("packages option = %v, want %q", got, "jq,ripgrep")
	}
	// And no bunker-specific apt field:
	if _, exists := cfg["apt"]; exists {
		t.Error(`generated config must not contain a bunker "apt" field`)
	}
}

// TestInitSettingsFromConfig_ReadsAptPackagesFromFeature verifies the
// pre-populate path reads packages back from the standard feature entry
// (comma-separated) into the wizard's space-separated field.
func TestInitSettingsFromConfig_ReadsAptPackagesFromFeature(t *testing.T) {
	existing := &config.ProjectConfig{
		Features: map[string]map[string]any{
			aptPackagesFeatureRef: {"packages": "jq,ripgrep"},
		},
	}
	s, enabled := initSettingsFromConfig(existing)
	if s.aptPackages != "jq ripgrep" {
		t.Errorf("aptPackages = %q, want %q", s.aptPackages, "jq ripgrep")
	}
	found := false
	for _, e := range enabled {
		if e == settingPackages {
			found = true
		}
	}
	if !found {
		t.Errorf("settingPackages should be enabled when the apt-packages feature is present; enabled=%v", enabled)
	}
}

// TestLoadConfig_ExpandsGhTokenBeforeAuth locks the ordering of the single
// riskiest line in loadConfig: config.ExpandProjectConfig(&cfg) must run
// before auth resolution reads GhToken, otherwise a raw ${VAR} reference
// would leak into the container instead of its resolved value.
func TestLoadConfig_ExpandsGhTokenBeforeAuth(t *testing.T) {
	ws := t.TempDir()
	dir := filepath.Join(ws, ".devcontainer")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	body := `{"customizations":{"claude-bunker":{"ghToken":"${CB_TEST_GH_TOKEN}"}}}`
	if err := os.WriteFile(filepath.Join(dir, "devcontainer.json"), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Setenv("CB_TEST_GH_TOKEN", "resolved-token-value")

	r := &runner{workspace: ws}
	r.loadConfig(bunkerFlags{})
	if r.projectCfg.GhToken != "resolved-token-value" {
		t.Errorf("ghToken not expanded in projectCfg: %q", r.projectCfg.GhToken)
	}
	if r.auth.GhToken != "resolved-token-value" {
		t.Errorf("auth.GhToken must be the EXPANDED token (expand must run before auth resolution): %q", r.auth.GhToken)
	}
}
